### ISSUE TITLE
[WopiHost] Rootpath as input param / can be override instead of fix in appSettings

### ISSUE THREAD

**Issue by natilux2** [petrsvihlik/WopiHost#112]
I have excel file in multiple location instead of predefined folder. How can I change the path of excel file when it is not come from  predefined folder (e.g: excel file doesn't come from "RootPath": ".\\wwwroot\\wopi-docs") ?

**Comment by petrsvihlik** [comment]
The `RootPath` can be overridden in many ways. Both the `WopiHost` and `WopiHost.Web` use `CreateDefaultBuilder` method to initialize the `Host`. This comes with the following configuration sources [out of the box](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#default-configuration):
- appSettings
- app secrets
- env variables
- command-line args

To initialize flat structures such as env variables, use the following key: `Wopi:StorageProviderOptions:RootPath`.

If you want to add more configuration sources, adjust the `ConfigureAppConfiguration` method as follows:
```c#
Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((context, config) =>
        {
          config.AddAzureKeyVault(...);
          config.AddIniFile(...)
        })
```

If you store your files in multiple locations, you'll need to adjust the implementation of the `WopiFileSystemProvider` or create your own implementation of the `IWopiStorageProvider`. First, you'll need to adjust the `WopiFileSystemProviderOptions` to accept `string[]` of paths instead of just a single `string` and then add an extra iterator to `GetWopiFile`(s) and `GetWopiContainer`(s) methods.
