### ISSUE TITLE
Will this project run on linux/.Net Core

### ISSUE THREAD

**Issue by gsvitak** [petrsvihlik/WopiHost#44]
Hello,

Thanks for the great sample. WIll this run on Linux and .Net Core? If yes which version of .Net Core would you suggest I try to play around?

Thanks,
G

**Comment by petrsvihlik** [comment]
Hi @gsvitak ,
if you want all the MS-FSSHTTP functionality (aka Cobalt) then you have to target the full .NET framework (e.g. net46) as it's dependent on MS's Microsoft.CobaltCore.dll which is only available for full FW. The MS-FSSHTTP is typically required for Word editing and other actions (see the discovery.xml of OOS2016/OWA2013 and look for requires="cobalt"). Interesting fact is that Office Online (365) doesn't require cobalt for almost any actions. However, you'd have to be an integration partner to integrate with it (see my [answer on SO](http://stackoverflow.com/questions/39062025/wopi-host-implementation-in-nodejs/39186295)).
Good thing is that ASP.NET Core can target net46 so you can still benefit from its features. However, it won't be a pure .NET Core application (you won't be able to run it on other platforms than windows, for instance). The main project - WopiHost targets both net46 and .net core (as you can see in the [project.json](https://github.com/petrsvihlik/WopiHost/blob/master/WopiHost/project.json)).
But if you clone the repo, delete the cobalt stuff, it should be possible to get it running on Linux - but it would be limited (e.g. Word would only support viewing). Excel should work fine, it doesn't require cobalt at all.

If you want to chat about that I've created a gitter room: https://gitter.im/ms-wopi/.

**Comment by gsvitak** [comment]
Thank you for the input. super helpful

**Comment by petrsvihlik** [comment]
hey @gsvitak ...have you been able to make it work? i replied to your message on gitter but didn't see any reply since then...

just one more information - because microsoft is [going to support only](https://blogs.office.com/2016/11/18/office-online-server-november-release/) the latest version of OOS, I'll be removing support for the old versions. and because the latest version of OOS doesn't require cobalt for 99% of actions, I'll remove cobalt support from this project as well (i might add it later as optional to support onenote file format...but i don't see it critical)

**Comment by gsvitak** [comment]
@petrsvihlik thanks for the reply. I commented in gitter so we can keep communication in one spot.

**Comment by petrsvihlik** [comment]
ideally, I'd like to make the changes this weekend. I'd like to preserve the current version in a separate branch just for reference...if you manage to do that sooner, feel free to submit a PR
