### ISSUE TITLE
Communication between Iframe and parent window

### ISSUE THREAD

**Issue by boagorudolph** [petrsvihlik/WopiHost#62]
I have an excel-online embedded document on an Iframe element. The file is served by a WOPI host to client. 

I want to be able have the Iframe communicate with the parent window the same way that an oline file served from OneDrive can communicate with its parent window using the Excel Services JavaScript API (https://msdn.microsoft.com/en-us/library/office/hh315812(v=office.14).aspx). I want to be able to read elements such as a cell that is in focus etc. 

Wopi protocol suggest using HTML PostMessage which has limitation as it does not allow for manipulation of the embedded file the same way Excel Services JavaScript API does.

Is there a way to achieve this with an Iframe embedded excel-oline file served through a WOPI host?

**Comment by petrsvihlik** [comment]
I'm afraid the only way to do that would be to host the host page (aka parent window) on the same domain as the OWA/OOS edit frames are hosted. Otherwise, the JS calls would be cross-origin requests and I'm not aware of any way of configuring CORS in OWA/OOS. That's why their documentation suggests using `postMessage` because that can easily overcome the cross domain issue.

I guess MS has CORS enabled for the Excel Services JavaScript API... not sure how else would they achieve it.

**Comment by boagorudolph** [comment]
The HTML PostMessage only modifies file's url parameters and reloads the file. It does not detect user interactions with the file contents.

**Comment by petrsvihlik** [comment]
Yeah, I know, it supports only some basic [operations](http://wopi.readthedocs.io/en/latest/scenarios/postmessage.html). That's why I suggested running both frames on the same domain. Otherwise, I have no idea...
